//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordRichPresenceForVisualStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordRichPresenceForVisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;C++&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;h&quot;, &quot;c&quot;, &quot;cc&quot;, &quot;hh&quot;, &quot;cpp&quot;, &quot;ipp&quot;, &quot;inl&quot;, &quot;c++&quot;, &quot;h++&quot;, &quot;hpp&quot; ],
        ///    &quot;ImageKey&quot;: &quot;cpp&quot;
        ///  },
        ///  &quot;GO&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;go&quot; ],
        ///    &quot;ImageKey&quot;: &quot;go&quot;
        ///  },
        ///  &quot;PHP&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;php&quot; ],
        ///    &quot;ImageKey&quot;: &quot;php&quot;
        ///  },
        ///  &quot;Ruby&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;rb&quot;, &quot;rbw&quot; ],
        ///    &quot;ImageKey&quot;: &quot;ruby&quot;
        ///  },
        ///  &quot;C#&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;cs&quot; ],
        ///    &quot;ImageKey&quot;: &quot;csharp&quot;
        ///  },
        ///  &quot;F#&quot;: {
        ///    &quot;Extensions&quot;: [ &quot;fs&quot;, &quot;fsi&quot;, &quot;fsx&quot;, &quot;fsscript&quot; ],
        ///    &quot;ImageKey&quot;: &quot;fsharp&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
    }
}
